### ISSUE TITLE
why net for train and pred is different?

### ISSUE THREAD

**Issue by CNevd** [wnzhang/deep-ctr#1]
the network for train and pred is different according to the code in fnn.py
for train is: data(x) -> dropout(x) -> full connect(z1) -> active(h1) -> full connect(z2) -> active(h2)  ---> 1 / (1 + T.exp(-T.dot(h2, w3) - b3))
for pred is: data(x) -> dropout(x) -> full connect(z1) -> active(h1) -> dropout(d1) -> full connect(d2) -> dropout(d2) ---> (1 / (1 + T.exp(-T.dot(d2, w3) - b3)))

is there any thing i've missed?

and when update feat_weights, why is b_size in (1 - 2. \* lambda_fm \* lr / b_size) is needed?

THS

**Comment by tianmingdu** [comment]
Hi CNevd,
Sorry about this confusing. 
You can ignore the dropout(x) as the parameter x_drop is  always assigned to 1.
The actual training procedure is: data(x) ->  full connect(z1) -> tanh_active(h1) -> dropout(d1) -> full connect_and_tanh_active(d2) ->dropout(d2) --->(1 / (1 + T.exp(-T.dot(d2, w3) - b3))).
The actual procedure of the prediction is: data(x) ->  full connect(z1) -> tanh_active(h1)  -> full connect(z2)-> tanh_active(h2) --->1 / (1 + T.exp(-T.dot(h2, w3) - b3)).
The fundamental difference between training process and prediction is only at dropout step.

Your second question I will double check with Weinan and will answer you soon.

Thanks.
Tianming

**Comment by wnzhang** [comment]
Hi CNevd,

b_size is not necessary but its makes the code more comprehensive and make the learning stable again the size of the mini-batch.

Thanks.
Weinan

**Comment by CNevd** [comment]
@tianmingdu @wnzhang  OK i know, thank you very much
