### ISSUE TITLE
do some configurations not mentioned?

### ISSUE THREAD

**Issue by lxmeng** [wnzhang/deep-ctr#2]
below is SNN_*'s result running on my envi, is there any configuration wrong causing the poor results...
## my command THEANO_FLAGS=mode=FAST_RUN,device=gpu3,floatX=float64,nvcc.fastmath=True,optimizer_including=cudnn  python *.py

Using gpu device 3: Tesla K40m (CNMeM is disabled)
../data/train.fm.txt
drop_mlp4da.py|ad:2997|drop:0.98|b_size:1000 | X:133465 | Hidden 0:200 | Hidden 1:300 | Hidden 2:100 | L_r:0.001 | activation1:tanh | lambda:0
training RBM
line: 133465
line: 200
Done epoch 1: 496.320000 seconds, MSE=2.042194
Done epoch 2: 495.180000 seconds, MSE=2.067020
Done epoch 3: 488.930000 seconds, MSE=2.081377
line: 300
Done epoch 1: 18.190000 seconds, MSE=52.485198
Done epoch 2: 19.510000 seconds, MSE=52.301880
Done epoch 3: 20.080000 seconds, MSE=51.954111
line: 100
Done epoch 1: 21.250000 seconds, MSE=57.726292
Done epoch 2: 20.790000 seconds, MSE=57.654725
Done epoch 3: 20.770000 seconds, MSE=57.515879
Training model:
training: 0m 10s
        Training Err:   0   0.496572435445  0.0974163483508
training error: 0m 3s
Test Err:0  0.431917535545  0.053397720153
test error: 0m 2s
training: 0m 10s
        Training Err:   1   0.498144730401  0.0973837941595
training error: 0m 3s
Test Err:1  0.428466824645  0.0530087656782
test error: 0m 3s
training: 0m 10s
        Training Err:   2   0.494184712123  0.097358012913
training error: 0m 4s
Test Err:2  0.416555924171  0.0525893110747
test error: 0m 3s
training: 0m 10s
        Training Err:   3   0.490345884187  0.0973344273793
training error: 0m 3s
Test Err:3  0.398964454976  0.052395568973
test error: 0m 3s
training: 0m 10s
        Training Err:   4   0.474640680618  0.0973187175469
training error: 0m 3s
Test Err:4  0.418818009479  0.0519934911369
test error: 0m 3s
## **Minimal test error is 0.431917535545 , at EPOCH 0**

Using gpu device 3: Tesla K40m (CNMeM is disabled)
../data/train.fm.txt
drop_mlp4da.py|ad:2997|drop:0.99|b_size:1000 | X:133465 | Hidden 0:200 | Hidden 1:300 | Hidden 2:100 | L_r:0.0005 | activation1:tanh | lambda:0
Training epoch 0, cost  0.0994964612935
Training epoch 1, cost  0.00828848277617
Training epoch 2, cost  0.00484525396831
Training epoch 0, cost  134.467684274
Training epoch 1, cost  134.398491925
Training epoch 2, cost  134.386115337
Training epoch 0, cost  152.707873105
Training epoch 1, cost  152.651793831
Training epoch 2, cost  152.644853724
Training model:
training: 0m 11s
        Training Err:   0   0.5 0.0975933509993
training error: 0m 4s
Test Err:0  0.5 0.0486215139663
test error: 0m 3s
training: 0m 11s
        Training Err:   1   0.51468813636   0.0971287952011
training error: 0m 4s
Test Err:1  0.566842654028  0.0490243392275
test error: 0m 3s
training: 0m 10s
        Training Err:   2   0.513200800344  0.0971307412489
training error: 0m 4s
Test Err:2  0.553879620853  0.0489829048535
test error: 0m 3s
training: 0m 10s
        Training Err:   3   0.51709338385   0.0971302388917
training error: 0m 3s
Test Err:3  0.559997156398  0.0489918453575
test error: 0m 3s
training: 0m 11s
        Training Err:   4   0.513745306555  0.0971290437782
training error: 0m 3s
Test Err:4  0.564237440758  0.0490177193574
test error: 0m 3s
training: 0m 10s
        Training Err:   5   0.511624808306  0.0971309889204
training error: 0m 4s
Test Err:5  0.571770616114  0.0489790098352
test error: 0m 3s
training: 0m 11s
        Training Err:   6   0.514979392466  0.097128609435
training error: 0m 4s
Test Err:6  0.573091943128  0.0490302115227
test error: 0m 3s
training: 0m 11s
        Training Err:   7   0.516966573944  0.0971283619885
training error: 0m 4s
Test Err:7  0.550987203791  0.0490390031933
test error: 0m 3s
training: 0m 10s
        Training Err:   8   0.518681280492  0.0971314928913
training error: 0m 4s
Test Err:8  0.566776777251  0.0489713436744
test error: 0m 3s
training: 0m 11s
        Training Err:   9   0.518882401743  0.0971282811621
training error: 0m 3s
Test Err:9  0.571286255924  0.0491369050573
test error: 0m 3s
training: 0m 11s
        Training Err:   10  0.51660899219   0.097128478358
training error: 0m 3s
Test Err:10 0.559154028436  0.0490346202497
test error: 0m 3s

**Comment by tianmingdu** [comment]
Hi lxmeng,
The reason why you get the poor results is the training file and the parameters. The default parameters are suitable for some bigger data.  Besides, you can find the size of file ../data/train.fm.txt is rather small and it's just a tool file. If you want to see more deep about this model, I would recommend you trying the repo at https://github.com/wnzhang/make-ipinyou-data. Hope this will answer your question.

Thanks.
Tianming
