### ISSUE TITLE
questions about initialization of level-0 weight W_0^i  and local FM

### ISSUE THREAD

**Issue by kelvinleen** [wnzhang/deep-ctr#4]
the 6th row of page 5 in the paper,  it's about the initialization of W_0^i(0 is the subscript and i is the superscript), W_0^i[0] is initial by w_i, W_0^i[1] by v_i^1。here i have a question：W_0^i[0] is a vector, as far as i understand, W_0^i[0] is the first row of matrix W_0^i,  initial by w_i means the whole elements of the vector are all w_i？ 

another question：as u say, FM is not fully connect， which means FM is only used in each field？  and if FM is only used in each field， then the second order interaction feature (< v_i, v_j > x_i \* x_j in fomula 6) is useless because in each field it's a one-hot encoding, so only one index of x_i is 1 and others are 0 in the field？  but if FM is used in the whole feature x, the parameters are same as 100 \* 1m, contradict with that FM reduces the parameters。 Am i misunderstand something?

**Comment by wnzhang** [comment]
1. 
   W_0^i[0] = w_i. it is a scalar.
   W_0^i[1:K] = v. it is a K-dim vector

2.
By "not fully connected", we meant the embedding layer, i.e. W_0, is not fully connected. As you can see from Fig.1., the first embedding layer is not fully connected: the nodes are separated by the dashed vertical lines.

**Comment by kelvinleen** [comment]
i am afraid i still cannot understand。  
1.W_0^i is a matrix with dim(K+1,end_i-start_i+1)，w_i is a scalar v^i is a vector(dim=k+1)， how to initialize W_0^i？ 
2.as u say, FM is separated by dashed lines, so it means FM just train in each field,  as we just have one hot encoding of each field， so the second order interaction of feature is useless？

**Comment by wnzhang** [comment]
1. W_0^i is initailized by FM parameters (w and v) for the field i.
2. FM is different from FNN. FM parameters are just used for initialization of the first layer of FNN.

**Comment by gash717** [comment]
@kelvinleen may misunderstand that "Fully Connected within each field" is relevant to FM.
I think "Fully Connected within each field" is only relevant to weights update in DNN.
Is my understanding correct with this? I'm sorry if I'm wrong.

**Comment by kelvinleen** [comment]
after reading the paper more times, i think i have had misunderstood something before. W_0 is initialized by w_i, and latent vector v_i, sizeof W_0 is (K+1)*N,where N is feature length,i.e. N=len(x). further more，it not full connect because each feature x_i is just connect to K+1, not to the whole hidden layer. and so reduce parameter. sorry for misunderstanding.

**Comment by wnzhang** [comment]
Yes. You are right :)
