### ISSUE TITLE
Code mistake?

### ISSUE THREAD

**Issue by cqhxping** [wnzhang/deep-ctr#5]
Is there an error in the following statement to update weight best_w3  in file FNN.py ?

best_w3=w1.get_value()

**Comment by tianmingdu** [comment]
there is no error for this statement, what kind of error did you encounter? please paste it here.

**Comment by cqhxping** [comment]
But I do think the correct one is as the follwing:
best_w3=w3.get_value()
Because best_w1=w1.get_value() and best_w3 need to be updated differently.

**Comment by tianmingdu** [comment]
You are correct! Although it would not effect the result in most cases, the initial weight for best_w1 should be w1.get_value(). Thank you!
