### ISSUE TITLE
How can we get the 1458/fm.model.txt?Thx

### ISSUE THREAD

**Issue by youngjt** [wnzhang/deep-ctr#6]
(1)In the file of FNN.py,train_file='../data/train.fm.txt' ,test_file='../data/test.fm.txt' , fm_model_file='../data/fm.model.txt' ,how can we get the three files from the ipinyou-data(https://github.com/wnzhang/make-ipinyou-data).

(2)In the file of fm.py, it can not find the package of features(from features import *).

Thank!

**Comment by wnzhang** [comment]
Please use fm.py code in this repository to get these files.
