### ISSUE TITLE
No moudle named features

### ISSUE THREAD

**Issue by liuxiaoxinhappy** [wnzhang/deep-ctr#8]
Hello,
In fm.py,I got "No moudle named features",what should I do with it?

**Comment by q252558242** [comment]
@tianmingdu @wnzhang Excuse me,I got the same problem.Would you like to tell us how to fix this problem?

**Comment by YingQian94** [comment]
There is no code using features in fm.py.So you can comment 'from features import *' in line  81.

**Comment by liuxiaoxinhappy** [comment]
Hi,
I have tried to comment 'from features import *' and run the fm.py,but I still have a question:
 **how can we get the model_file? just like the  file fm.model.txt under the folder data ?**

**Comment by YingQian94** [comment]
I think the model_file is trained through fm.py.And I use the same train.fm.txt and test.fm.txt in data,but I got different model_file. @tianmingdu @wnzhang Excuse me,Can you explain why I got different model while using the same train.fm.txt and test.fm.txt. PS: I use featindex.fm.txt as the index file.

**Comment by wnzhang** [comment]
Hi guys, sorry actually this project is quite old. We have not use theano since tensorflow's birth.
I recommend you to try our new repository with FM, FNN, and our newer model PNN
https://github.com/Atomu2014/product-nets
with more explanations in this paper https://arxiv.org/pdf/1611.00144.pdf
Thanks.
Weinan

**Comment by liuxiaoxinhappy** [comment]
OK，I think I have understand the method to got model_file. 
thanks a lot!

**Comment by liuxiaoxinhappy** [comment]
Hello Weinan Zhang,
Thanks a lot for your new  repository, and I wil try it soon.

**Comment by YingQian94** [comment]
@wnzhang Thanks a lot for your help.
